services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_DATABASE=
    volumes:
      - /path/to/data:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
      
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=Europe/Paris
      - MYSQL_DATABASE=b
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - /path/to/data:/config
    restart: unless-stopped
